# services:

#   app:
#     build: .
#     container_name: crypto_data_modelling_app
#     network_mode:
#     env_file:
#       - .env
#     environment:
      

#     volumes:
#       - ./etl:/app/etl
#       - ./tests:/app/tests
#       - ./config:/app/config
#       - ./data:/app/data
#       - ./dags:/app/dags

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: broker
    container_name: broker-crypto
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-crypto:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  jobmanager:
    image: pyflink/playgrounds:1.13.0-rc2
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./jars:/opt/flink/lib 

  taskmanager:
    image: pyflink/playgrounds:1.13.0-rc2
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./jars:/opt/flink/lib  

  # pyflink:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - jobmanager
  #     - broker
  #   volumes:
  #     - ./jars:/opt/flink/lib
  #     - ./app:/opt/flink/app
  #   working_dir: /opt/flink/app
  #   command: ["python3", "test.py"]
